import './global.css';
import { Lato } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@petsy/auth-config/server';

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lato',
});

export const metadata = {
  title: 'Welcome to petsy',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${lato.variable} font-sans`}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
