import { ClerkProvider } from '@clerk/nextjs';
import { Lato } from 'next/font/google';
import './global.css';

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lato',
});

export const metadata = {
  title: 'Welcome to petsy',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${lato.variable} font-sans bg-body-background`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
