import { ClerkProvider } from '@clerk/nextjs';
import { Montserrat } from 'next/font/google';
import './global.css';
import { Toaster } from '@petsy/shadcn-components';

const monserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-montserrat',
});

export const metadata = {
  title: 'Welcome to petsy',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${monserrat.variable} font-sans bg-body-background`}>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
