name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  lint:
    uses: ./.github/workflows/ci.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    needs: [lint]
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.SEMANTIC_RELEASE_ID }}
          private_key: ${{ secrets.SEMANTIC_RELEASE_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      #   TODO: need to check high vulnerabilities
      # - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
      #   run: pnpm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: pnpm release
